In [1]:
pip install torch torchvision torchaudio

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
import numpy as np

Creating a Tensor 

In [3]:
#Using Empty 
a = torch.empty(2,3)

In [32]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
type(a)

torch.Tensor

In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand 
torch.rand(3,4)

tensor([[0.2046, 0.8338, 0.0480, 0.6365],
        [0.2832, 0.1740, 0.6868, 0.3869],
        [0.7432, 0.9377, 0.5994, 0.5350]])

In [9]:
#using mannual seed
torch.manual_seed(100)
torch.rand(4,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [10]:
#using mannual seed
torch.manual_seed(100)
torch.rand(4,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [11]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [12]:
x_data

tensor([[1, 2],
        [3, 4]])

In [13]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [14]:
x_np

tensor([[1, 2],
        [3, 4]])

In [15]:
#Attributes of a Tensor
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [16]:
tensor = torch.ones(4, 4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
tensor

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
print(f"Last Row: {tensor[-1,...]}")

Last Row: tensor([1., 0., 1., 1.])


In [19]:
roll_no = ([[12,45,78],
           [87,67,89],
           [13,65,90],
           [23,78,43]])
roll_no

[[12, 45, 78], [87, 67, 89], [13, 65, 90], [23, 78, 43]]

In [20]:
print(f"First Row: {roll_no[0]}")

First Row: [12, 45, 78]


In [21]:
print(f"Second Row: {roll_no[1]}")

Second Row: [87, 67, 89]


In [22]:
print(f"Third Row: {roll_no[2]}")

Third Row: [13, 65, 90]


In [23]:
print(f"Fourth Row: {roll_no[3]}")

Fourth Row: [23, 78, 43]


In [24]:
roll_no = np.array(roll_no)   # convert list to NumPy array
print(f"First Column: {roll_no[:, 0]}")  

First Column: [12 87 13 23]


In [25]:
print(f"Second Column: {roll_no[:, 1]}")  

Second Column: [45 67 65 78]


In [26]:
print(f"Third Column: {roll_no[:, 2]}")  

Third Column: [78 89 90 43]


In [27]:
# arange
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [28]:
# using linspace
print("using linspace ->", torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [29]:
# using eye
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [30]:
# using full
print("using full ->", torch.full((3, 2), 3.8))

using full -> tensor([[3.8000, 3.8000],
        [3.8000, 3.8000],
        [3.8000, 3.8000]])


In [33]:
#Tensor Shapes 
d = torch.tensor([[1,2,3],[11,90,65]])
d

tensor([[ 1,  2,  3],
        [11, 90, 65]])

In [34]:
d.shape

torch.Size([2, 3])

In [39]:
torch.empty_like(d)

tensor([[      4413716630960, 4575657222473777152, 4575657222473777152],
        [4575657222473777152, 4575657222473777152, 4575657222473777152]])

In [40]:
torch.ones_like(d)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [41]:
torch.zeros_like(d)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [47]:
torch.rand_like(d,dtype=torch.float16)

tensor([[0.3696, 0.8530, 0.2988],
        [0.5020, 0.2944, 0.9663]], dtype=torch.float16)

In [48]:
d.dtype

torch.int64

In [53]:
#assign Data type
c = torch.tensor([1.0,2.98,11.66,7,22,87.99], dtype=torch.int16)
c

tensor([ 1,  2, 11,  7, 22, 87], dtype=torch.int16)

In [54]:
f = torch.tensor([2,7,8,9,10], dtype=torch.float64)
f

tensor([ 2.,  7.,  8.,  9., 10.], dtype=torch.float64)

In [55]:
h = torch.rand(4,5)
h

tensor([[0.6476, 0.3430, 0.3182, 0.5261, 0.0447],
        [0.5123, 0.9051, 0.5989, 0.4450, 0.7278],
        [0.4563, 0.3389, 0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356, 0.3039, 0.6726]])

In [56]:
#mathematical Operation 
h + 2

tensor([[2.6476, 2.3430, 2.3182, 2.5261, 2.0447],
        [2.5123, 2.9051, 2.5989, 2.4450, 2.7278],
        [2.4563, 2.3389, 2.6211, 2.5530, 2.6896],
        [2.3687, 2.9053, 2.8356, 2.3039, 2.6726]])

In [57]:
h - 2

tensor([[-1.3524, -1.6570, -1.6818, -1.4739, -1.9553],
        [-1.4877, -1.0949, -1.4011, -1.5550, -1.2722],
        [-1.5437, -1.6611, -1.3789, -1.4470, -1.3104],
        [-1.6313, -1.0947, -1.1644, -1.6961, -1.3274]])

In [58]:
h * 2

tensor([[1.2953, 0.6861, 0.6365, 1.0522, 0.0893],
        [1.0247, 1.8102, 1.1977, 0.8900, 1.4557],
        [0.9125, 0.6777, 1.2423, 1.1060, 1.3792],
        [0.7375, 1.8105, 1.6712, 0.6078, 1.3452]])

In [59]:
h / 2

tensor([[0.3238, 0.1715, 0.1591, 0.2630, 0.0223],
        [0.2562, 0.4525, 0.2994, 0.2225, 0.3639],
        [0.2281, 0.1694, 0.3106, 0.2765, 0.3448],
        [0.1844, 0.4526, 0.4178, 0.1520, 0.3363]])

In [66]:
#Element wise Operation 
ab = torch.rand(2,3)
gh = torch.rand(2,3)

In [67]:
ab

tensor([[0.9798, 0.5548, 0.6868],
        [0.4920, 0.0748, 0.9605]])

In [68]:
gh

tensor([[0.3271, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])

In [69]:
ab + gh

tensor([[1.3069, 0.5650, 1.6384],
        [0.7776, 0.3072, 1.8746]])

In [70]:
torch.cuda.is_available()

False